apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: test # service 是 namespace 级别的对象
spec:
  selector: # Pod选择器
    app: mysql
  type: NodePort # service 的类型
  ports:
    - name: http
      port: 3306       # service 的端口号
      targetPort: 3306 # 对应到 Pod 上的端口号
      protocol: TCP  # 还支持 udp，http 等